#!/bin/bash

# to capture tcp traffic between client and sim execute this script
# hot ^c to terminate capture and lauch wireshark

# sudo /usr/sbin/tcpdump -i lo -X -w /scratch/tcpout.pcap portrange 6300-6400
sudo /usr/sbin/tcpdump -i eth0 -X -w /scratch/tcpout.pcap portrange 6300-6400
/usr/sbin/wireshark /scratch/tcpout.pcap &
