# This file was automatically generated on Fri 30 Jan 2015 11:13:20 GMT from
# source: /home/hgv27681/tmp/medipix/etc/makeIocs/merlin.xml
# 
# *** Please do not edit this file: edit the source file instead. ***
# 
#cd "/home/hgv27681/tmp/medipix/iocs/merlin"
< envPaths.linux
errlogInit(20000)

epicsEnvSet "EPICS_TS_MIN_WEST", '0'


# Loading libraries
# -----------------

# Device initialisation
# ---------------------


dbLoadDatabase "../../dbd/merlin.dbd"
merlin_registerRecordDeviceDriver(pdbbase)

< /local/config/xrd_config.epics


epicsEnvSet("DETECTOR", "merlin")

epicsEnvSet("PREFIX", "$(SECTOR)$(DETECTOR)$(SUFFIX):")


epicsEnvSet("COMMAND_PORT", "Merlin.CAMcmd")
epicsEnvSet("STATUS_PORT", "6341")
epicsEnvSet("DATA_PORT", "Merlin.CAMdata")
epicsEnvSet("DATA_PORT_BUFFERS", "50")
epicsEnvSet("PORT",   "Merlin.CAM")
epicsEnvSet("QSIZE",  "20")
epicsEnvSet("XSIZE",  "512")
epicsEnvSet("YSIZE",  "512")
epicsEnvSet("NCHANS", "2048")
epicsEnvSet("MODEL", "3") 			#detectorType: 0 = Merlin, 1 = Medipix_XBPM, 2 = UoM_BPM, 3 = Quad Merlin

drvAsynIPPortConfigure("Merlin.CAMcmd", "164.54.101.21:6341", 100, 0, 0)

drvAsynIPPortConfigure("Merlin.CAMdata", "164.54.101.21:6342", 100, 0, 0)

# medipixDetectorConfig(portName, commandPort, dataPort, maxSizeX, maxSizeY, ,detectorType maxBuffers, maxMemory)
medipixDetectorConfig($(PORT), $(COMMAND_PORT), $(DATA_PORT), $(XSIZE), $(YSIZE), $(MODEL), $(DATA_PORT_BUFFERS), -1)

# driver specific TRACING 
#  0x101 = less verbose, 0x301 = most verbose, 0x01 = errors only
#asynSetTraceMask($(PORT), 0, 255)

dbLoadRecords("$(ADCORE)/db/ADBase.template", "P=$(PREFIX),R=cam1:,PORT=$(PORT),ADDR=0,TIMEOUT=1")
dbLoadRecords("$(ADCORE)/db/NDFile.template", "P=$(PREFIX),R=cam1:,PORT=$(PORT),ADDR=0,TIMEOUT=1")
dbLoadRecords("$(ADMEDIPIX)/db/medipix.template", "P=$(PREFIX),R=cam1:,PORT=$(PORT),ADDR=0,TIMEOUT=1")

# Create a standard arrays plugin
NDStdArraysConfigure("Image1", 5, 0, "$(PORT)", 0, 0)
dbLoadRecords("$(ADCORE)/db/NDPluginBase.template","P=$(PREFIX),R=image1:,PORT=Image1,ADDR=0,TIMEOUT=1,NDARRAY_PORT=$(PORT),NDARRAY_ADDR=0")
dbLoadRecords("$(ADCORE)/db/NDStdArrays.template", "P=$(PREFIX),R=image1:,PORT=Image1,ADDR=0,TIMEOUT=1,TYPE=Int32,FTVL=LONG,NELEMENTS=262144")

# Load all other plugins using commonPlugins.cmd
< $(ADCORE)/iocBoot/commonPlugins.cmd

set_requestfile_path("$(ADMEDIPIX)/medipixApp/Db/")


# Final ioc initialisation
# ------------------------
#cd "/home/hgv27681/tmp/medipix/iocs/merlin"
dbLoadRecords '../../db/merlin_expanded.db'

iocInit()


# save things every thirty seconds
create_monitor_set("auto_settings.req", 30,"P=$(PREFIX)")

