/* This file was automatically generated on Fri 30 Jan 2015 11:13:20 GMT from
 * source: /home/hgv27681/tmp/medipix/etc/makeIocs/merlin.xml
 * 
 * *** Please do not edit this file: edit the source file instead. ***
 *  */
#include "epicsExit.h"
#include "epicsThread.h"
#include "iocsh.h"

int main(int argc, char *argv[])
{
    if(argc>=2) {
        iocsh(argv[1]);
        epicsThreadSleep(.2);
    }
    iocsh(NULL);
    epicsExit(0);
    return 0;
}

