name: Publish
on:
  push:
    tags:
      - '*'  # all tags
  workflow_dispatch:   # allow manual triggering
    inputs:
      deploy:
        description: 'Deploy documentation'
        type: boolean
        required: true
        default: false

jobs:

  build-docs:
    name: Build Sphinx Docs
    uses: ./.github/workflows/build-docs.yml

  publish-docs:
    name: Publish Sphinx Docs
    runs-on: ubuntu-latest
    needs: build-docs

    steps:
    - name: Deploy Information
      if: ${{ github.event.inputs.deploy }}
      run: |
        echo "The docs will be published from this workflow run."

    - name: Download Docs Artifact
      uses: actions/download-artifact@v4
      with:
        name: docs-html
        path: docs-html

    - name: Publish Docs
      uses: peaceiris/actions-gh-pages@v3.8.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs-html
